package io.github.og4dev.advice;

import io.github.og4dev.annotation.AutoResponse;
import io.github.og4dev.dto.ApiResponse;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;
import org.springframework.core.MethodParameter;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.http.server.ServerHttpResponse;
import org.springframework.http.server.ServletServerHttpResponse;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.servlet.mvc.method.annotation.ResponseBodyAdvice;

/**
 * Global response interceptor that automatically wraps REST controller outputs into the
 * standardized {@link ApiResponse} format.
 * <p>
 * This wrapper is conditionally activated <b>only</b> for controllers or specific methods
 * annotated with the {@link AutoResponse @AutoResponse} annotation. It provides a seamless
 * developer experience by eliminating the need to manually return {@code ResponseEntity<ApiResponse<T>>}
 * from every controller method.
 * </p>
 * <h2>Core Functionalities:</h2>
 * <ul>
 * <li><b>Automatic Encapsulation:</b> Intercepts raw DTOs, Lists, or primitive responses and packages
 * them into the {@code content} field of an {@code ApiResponse}.</li>
 * <li><b>Status Code Preservation:</b> Dynamically reads the current HTTP status of the response
 * (e.g., set via {@code @ResponseStatus(HttpStatus.CREATED)}) and ensures it is accurately
 * reflected in the final {@code ApiResponse}.</li>
 * <li><b>Safety Mechanisms:</b> Intelligently skips wrapping if the response is already formatted
 * to prevent double-wrapping errors or interference with standard error handling protocols.</li>
 * </ul>
 *
 * @author Pasindu OG
 * @version 1.4.0
 * @see AutoResponse
 * @see ApiResponse
 * @see ResponseBodyAdvice
 * @since 1.4.0
 */
@RestControllerAdvice(annotations = AutoResponse.class)
@SuppressWarnings("unused")
public @NullMarked class GlobalResponseWrapper implements ResponseBodyAdvice<Object> {

    /**
     * Determines whether the current response should be intercepted and wrapped.
     * <p>
     * To guarantee application stability and adherence to standard HTTP protocols, this method
     * specifically <b>excludes</b> the following return types from being wrapped:
     * </p>
     * <ul>
     * <li>{@link ApiResponse} - Prevents recursive double-wrapping (e.g., {@code ApiResponse<ApiResponse<T>>}).</li>
     * <li>{@link ResponseEntity} - Skips manual responses to respect developer's explicit configurations.</li>
     * <li>{@link ProblemDetail} - Excludes RFC 9457 error responses generated by exception handlers.</li>
     * <li>{@link String} - Bypasses raw strings to prevent {@code ClassCastException} when Spring utilizes
     * the {@code StringHttpMessageConverter}.</li>
     * </ul>
     *
     * @param returnType    The return type of the controller method.
     * @param converterType The selected HTTP message converter.
     * @return {@code true} if the body should be wrapped; {@code false} if it should be skipped.
     */
    @Override
    public @NullMarked boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
        Class<?> type = returnType.getParameterType();
        return !ApiResponse.class.isAssignableFrom(type) &&
                !ResponseEntity.class.isAssignableFrom(type) &&
                !ProblemDetail.class.isAssignableFrom(type) &&
                !String.class.isAssignableFrom(type);
    }

    /**
     * Intercepts the response body before it is written to the output stream and encapsulates it
     * within an {@link ApiResponse}.
     * <p>
     * This method extracts the actual HTTP status code set on the current response (defaulting to 200 OK).
     * Based on whether the status code represents a success (2xx) or another state, it dynamically
     * assigns an appropriate message ("Success" or "Processed") to the API response.
     * </p>
     *
     * @param body                  The raw object returned by the controller method.
     * @param returnType            The return type of the controller method.
     * @param selectedContentType   The selected content type for the response.
     * @param selectedConverterType The selected HTTP message converter.
     * @param request               The current server HTTP request.
     * @param response              The current server HTTP response.
     * @return The newly wrapped {@code ApiResponse} object ready to be serialized.
     */
    @Override
    public @Nullable Object beforeBodyWrite(@Nullable Object body, MethodParameter returnType, MediaType selectedContentType, Class<? extends HttpMessageConverter<?>> selectedConverterType, ServerHttpRequest request, ServerHttpResponse response) {
        int statusCode = HttpStatus.OK.value();

        // Extract the dynamically set HTTP status code (e.g., from @ResponseStatus)
        if (response instanceof ServletServerHttpResponse serverHttpResponse) {
            statusCode = serverHttpResponse.getServletResponse().getStatus();
        }

        HttpStatus httpStatus = HttpStatus.valueOf(statusCode);

        // Wrap the payload and generate the final format
        return ApiResponse.status(httpStatus.is2xxSuccessful() ? "Success" : "Processed", body, httpStatus).getBody();
    }
}